# Generated by Django 4.2.6 on 2023-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mecanico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('especialidad', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
