# Generated by Django 4.2.6 on 2023-12-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mecanico', '0004_registro_mecanico_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro_mecanico',
            table='Registro_mecanico',
        ),
    ]
